### ISSUE TITLE
All contributors

### ISSUE THREAD

**Issue by davidbieder** [cultivate-software/render-with-decorators#5]
Tool:
https://github.com/all-contributors/all-contributors

Example:
https://github.com/testing-library/react-testing-library

**Comment by jeromeweiss** [comment]
### How to use with CLI:
- install CLI to dev-dependencies (https://allcontributors.org/docs/en/cli/installation)
- **only if no .all-contributorsrc file exist:** use init command to initially setup configuration
- optional: setup two own scripts
- optional: change the configuration in .all-contributorsrc file
- use the "add command" to add new contributors > won't work without emoji! (https://allcontributors.org/docs/en/cli/usage)
- use the "generate command" to automatically overwrite the batch and contributor table in the README.md
- all changes needs to be pushed manually

### How to use with bot:
- install the bot and select the repositories the bot should be active > already done! (https://allcontributors.org/docs/en/bot/installation)
- write the add command in a comment of a PR (https://allcontributors.org/docs/en/bot/usage)
- this creates a new PR with the updated README.md and .all-contibutorsrc files containing the new contributor

## Important learnings:
- merging auto-generated PR from all-contributors bot will raise the release by one bugfix version (e.g. 1.0.1 > 1.0.2)
- using the add command without emoji does not work > but manually removing emoji in IDE works
- a wrong contributor will be created when contributor name is the same like an emoji and no emoji is used in the add command
- **when using the bot:** the auto-generated PR always contains changes in the README and configuration files > does another PR changes this as well and will be merged before, this impeded the rebase on GitHub
        - manually rebasing and solving conflicts in IDE does not help
        - based on branch-protection rules only a rebase is possible
- closing the auto-generated PR bot not delete the branch leads to the following problem:
        - using the add contributor command with the same contributor name will use the old existing branch for the new PR
        - the new auto-generated PR then contains all the old and new commits
        - it's not possible to rebase the new PR to the main branch

**Comment by jeromeweiss** [comment]
### Conclusion:
- the standard CLI and bot usage does not finally automate the complete process
- if all contributors shouldn't have emojis to describe what they've contributed, the emojis need to be removed manually
- no matter if bot or CLI - both processes could be controlled with e.g. a custom github workflow and/ or own scripts that handle e.g. merging PRs to add a contributor or deleting emojis from the contributors somewhere in the process
- using the CLI would maybe result in more control over the releasing and editing process and does not require a separate PR for adding contributors
