### ISSUE TITLE
Issue Template

### ISSUE THREAD

**Issue by davidbieder** [cultivate-software/render-with-decorators#6]
Example:
https://github.com/testing-library/react-testing-library/tree/main/.github

**Comment by jeromeweiss** [comment]
Additional links to e.g. Codebox or template-repo could be added to Bugfix template

Example:
![Image](https://user-images.githubusercontent.com/59569084/221245425-c63474d4-0d53-4c56-99c2-221e6e0c9ef7.png)

Link to template-repo: https://github.com/testing-library/dom-testing-library-template
Link to Codebox: https://codesandbox.io/s/5z6x4r7n0p

**Comment by jeromeweiss** [comment]
Added template for bug fixes and feature requests based on version 2.0.6
